DROP DATABASE IF EXISTS SASENAI;

CREATE DATABASE SASENAI;

USE SASENAI;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45) 
    , TURMA VARCHAR(45)
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE COORDENADOR (
	IDCOORDENADOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , CURSO VARCHAR(45)
    , SENHA VARCHAR(45)
    , PRIMARY KEY (IDCOORDENADOR)
);

CREATE TABLE AUTORIZACAO (
	IDAUTORIZACAO INT NOT NULL AUTO_INCREMENT
    , IDALUNO INT NOT NULL
    , IDCOORDENADOR INT NOT NULL
    , DTCRIACAO DATE
    , DTSAIDA TIME
    , PRIMARY KEY (IDAUTORIZACAO)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
    , FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (IDCOORDENADOR)
);

INSERT INTO ALUNO (NOME, TURMA) VALUES ("ROSSI", "12");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("JARA", "29");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("MAGALLAN", "6");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("IZQUIERDOZ", "21");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("OLAZA", "20");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("BARRIOS", "16");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("NANDEZ", "15");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("BENEDETTO", "18");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("BUFFARINI", "24");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("VILLA", "22");

INSERT INTO COORDENADOR (NOME, CURSO, SENHA) VALUES ("GUILLERMO SCHELOTTO", "TECNICO", "BOCAJUNIOR");