SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBSA;
CREATE DATABASE DBSA;

USE DBSA;

CREATE TABLE CURSO (
    IDCURSO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY(IDCURSO)
);

CREATE TABLE CORDENADOR (
    IDCORDENADOR INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY (IDCORDENADOR)
);

CREATE TABLE COORDENA (
    IDCORDENADOR INT NOT NULL
    , IDCURSO INT NOT NULL
    , PRIMARY KEY(IDCORDENADOR,IDCURSO)
    , FOREIGN KEY(IDCORDENADOR) REFERENCES CORDENADOR (IDCORDENADOR)
    , FOREIGN KEY(IDCURSO) REFERENCES CURSO (IDCURSO)
);

CREATE TABLE PORTEIRO (
    IDPORTEIRO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , PRIMARY KEY (IDPORTEIRO)
);

CREATE TABLE ALUNO (
    IDALUNO INT NOT NULL AUTO_INCREMENT
    , IDCURSO INT
    , MATRICULA VARCHAR(45)
    , NOME VARCHAR(100)
    , DTNASCIMENTO DATE
    , EMAIL VARCHAR(100)
    , PRIMARY KEY (IDALUNO)
    , FOREIGN KEY(IDCURSO) REFERENCES CURSO (IDCURSO)
);

CREATE TABLE SOLICITACAO (
    IDSOLICITACAO INT
    , IDALUNO INT
    , DHSOLICITADO DATETIME
    , DHSAIDA DATETIME
    , MOTIVO VARCHAR(250)
    , IDCORDENADOR INT
    , DHAPROVADO DATETIME
    , APROVADO ENUM('SIM', 'NAO')
    , IDPORTEIRO INT
    , DHLIBERADO DATETIME
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
    , FOREIGN KEY (IDCORDENADOR) REFERENCES CORDENADOR (IDCORDENADOR)
    , FOREIGN KEY (IDPORTEIRO) REFERENCES PORTEIRO (IDPORTEIRO)
    , PRIMARY KEY (IDSOLICITACAO)
);


/* INSERTS DE TESTE PRECISAM SOFRER ALTERAÇÕES PARA QUE POSSAM FUNCIONAR NO NOVO SISTEMA 

INSERT INTO ALUNO (NOME, TURMA) VALUES ("ROSSI", "12");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("JARA", "29");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("MAGALLAN", "6");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("IZQUIERDOZ", "21");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("OLAZA", "20");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("BARRIOS", "16");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("NANDEZ", "15");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("BENEDETTO", "18");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("BUFFARINI", "24");
INSERT INTO ALUNO (NOME, TURMA) VALUES ("VILLA", "22");

INSERT INTO COORDENADOR (NOME, CURSO, SENHA) VALUES ("GUILLERMO SCHELOTTO", "TECNICO", "BOCAJUNIOR");

*/